### ISSUE TITLE
Testes internos realizados pela equipe TB

### ISSUE THREAD

**Issue by rdurl0** [Transparencia-Brasil/transparencia.org.br#19]
O resultado dos testes feito pela equipe da Transparência Brasil está organizado na planilha:

https://docs.google.com/spreadsheets/d/1ir0jFdc8y0R1JTDfxmNLKo5VvB39mGLIQgBX2KZZmy4/edit#gid=2079649972

**Comment by wgnann** [comment]
Precisa testar upload e envio de email, pois não foi coberto pelo conjunto de testes.

**Comment by rdurl0** [comment]
Incluído novos testes para serem feitos até quarta (31/03):

* Publicação no blog
* Upload de arquivos em "Publicações"
* Alteração de imagens de carrossel da home
* testar fluxo de newsletter (adicionar newsletter e mandar e-mail de teste)
* testar fluxo de doações (testar a doação e verificar notificações)
* testar fluxo de novos associados (testar inclusão e remoção de novo associado e verificar notificações)
* testar fluxo de inclusão de novo usuário (incluir novos usuários e remover, verificar notificações)

https://docs.google.com/spreadsheets/d/1ir0jFdc8y0R1JTDfxmNLKo5VvB39mGLIQgBX2KZZmy4/edit#gid=1285875435

**Comment by studiocuboweb** [comment]
@rdurl0 pode fechar esse issue aqui?
