### ISSUE TITLE
problema com o composer

### ISSUE THREAD

**Issue by wgnann** [Transparencia-Brasil/transparencia.org.br#20]
O composer.json está chamando um post-install que está matando o deploy. Ele procura alguma coisa que parece não existir na instância da Azure e tenta fazer outras coisas como criar um SALT, o que não precisa no nosso caso.

Remover o post-install parece ter resolvido.

**Comment by studiocuboweb** [comment]
@wgnann 
Talvez esse link tenha algo relacionado só para documentação:
https://github.com/loadsys/CakePHP-Skeleton/issues/115

Como eu não sei dizer se a instalação desse cakephp foi feita da maneira correta (utilizando o composer ou simplesmente fazendo download do código via git) se você tirar o post-install do composer funcionou o deploy, então acabei de remove-lo. Fiz um commit no master mesmo:

https://github.com/Transparencia-Brasil/transparencia.org.br/commit/adb9abfc8e7813804e3b5a91745a44b3cdba970a

Favor validar e se estiver tudo OK fechar o ticket

**Comment by wgnann** [comment]
Deploy funcionou a contento.
