### ISSUE TITLE
problema com link simbólico

### ISSUE THREAD

**Issue by wgnann** [Transparencia-Brasil/transparencia.org.br#21]
O deployer do Azure não gosta de link simbólico. Na versão de testes, eu havia meramente logado na instância por SSH e criado os links. Mas o fato é que os links não aparecem depois do deploy a menos que coloquemos um trigger no composer. Ficou assim:

```
    "scripts": {
        "post-autoload-dump": "Cake\\Composer\\Installer\\PluginInstaller::postAutoloadDump",
        "post-create-project-cmd": [
            "@/bin/ln -s /home/site/wwwroot/webroot/uploads /home/site/wwwroot/webroot/downloads",
            "@/bin/ln -s /home/site/wwwroot/webroot/images /home/site/wwwroot/webroot/img"
        ]
    }
```

**Comment by studiocuboweb** [comment]
@wgnann
Adicionei essas linhas no composer.json e já está commitado no master mesmo.

Commits:
https://github.com/Transparencia-Brasil/transparencia.org.br/commit/d09e4c7f7705b7d90920338fa139617625e23f59
https://github.com/Transparencia-Brasil/transparencia.org.br/commit/6dbafda98fa9750bf85e1efba0a7c8a1f82f01d1

Acabei mandando dois pq primeiramente eu ia configurar apenas a pasta de downloads, mas fazendo uma pesquisa no código vi que a pasta img também é bastante utilizada...

Favor testar e se estiver tudo Ok fechar o issue.

**Comment by wgnann** [comment]
Consegui abrir uma imagem do `/img` e um arquivo do `/downloads`.
