### ISSUE TITLE
mudar branch principal de main para master

### ISSUE THREAD

**Issue by wgnann** [Transparencia-Brasil/transparencia.org.br#22]
O deployer espera `master` em vez de `main`.

**Comment by studiocuboweb** [comment]
@wgnann @andremotasc 

Acabei de mudar o branch main para master, deletei o branch main do repositório, mas eu acredito que vocês vão precisar apagar o branch main no local. Tente dar um git fetch, se não apagar, então é necessário fazer o seguinte procedimento:

git checkout master
git pull
git branch -d main (deleta o branch local)

Passo a passo em: https://stevenmortimer.com/5-steps-to-change-github-default-branch-from-master-to-main/

ticket do trello (controle para o André): https://trello.com/c/smKRnC2G/115-migracao-azure-site-tb-mudar-branch-main-para-master-no-github

**Comment by wgnann** [comment]
Dei um clone direto do repositório, por garantia e funcionou.
