### ISSUE TITLE
algum mecanismo antibot para inscrição no newsletter

### ISSUE THREAD

**Issue by wgnann** [Transparencia-Brasil/transparencia.org.br#24]

**Comment by studiocuboweb** [comment]
@mgaldino @JnCoe @rdurl0 
O captcha está implementado conforme esse pull request:
https://github.com/Transparencia-Brasil/transparencia.org.br/pull/34

Irei publicar em produção na segunda feira umas 10:00 horas. dessa forma vocês conseguem testar durante a semana, já que esse fluxo é crítico pois envolve:

- Cadastro na newsletter (rodapé, e página da newsletter)
- Cadastro de Associados
- Login de associados para renovação
- Contato

procedimentos de teste no site em produção https://www.transparencia.org.br/:

1. Na [home](https://www.transparencia.org.br/) assinar a newsletter que está footer. (OK se aparecer aquela mensagem para validar o email ou email já cadastrado)
2. Na [página de contato](https://www.transparencia.org.br/contato) preencher o formulário (OK se aparecer mensagem de enviado com sucesso)
3. Na mesma [página de contato](https://www.transparencia.org.br/contato), tentar assinar a newsletter novamente (como existem dois formulários, deu erro no meu primeiro teste pq conflitou o form do rodapé com o do cadastro. eu corrigi, mas é bom vocês testarem)
4. Na [página de contato ](https://www.transparencia.org.br/contato)selecionar Autorizo receber as comunicações da Transparência Brasil relativas às suas atividades e projetos com um email que ainda não está cadastrado no banco. (OK se o email foi salvo na base. Se o email não foi salvo, verificar se ele já existe.)
5. Na página Para renovar sua associação, [clique aqui](https://www.transparencia.org.br/apoie/doacoes).
5.1. Colocar um CPF que não existe. (OK se retornar "CPF não encontrado.")
5.2. Colocar um CPF existente. (OK se redirecionar para página de confirmação dos dados)
6. [Página cadastro novo associado](https://www.transparencia.org.br/apoie/associados). 
6.1. Preencher o cadastro com um CPF inexistente. (OK se o cadastro for concluído)
6.2. Colocar um CPF existente (OK se aparecer uma mensagem de usuário já cadastrado)

Aviso vocês quando for publicado

**Comment by studiocuboweb** [comment]
Publicado em produção. 

Aguardando validação da Transparência Brasil em https://www.transparencia.org.br/

Conforme roteiro de teste na descrição desse issue.

Se estiver tudo certo, favor fechar ou me avisar para que eu feche esse issue.

**Comment by studiocuboweb** [comment]
Ninguém respondeu. creio que o recaptcha esteja funcionando. Estou fechando o issue, qualquer problema criamos outro ou reabrimos esse
