### ISSUE TITLE
debug precisa ser false no app.php

### ISSUE THREAD

**Issue by wgnann** [Transparencia-Brasil/transparencia.org.br#27]
No #25 ele mostra que o env() não configura valor padrão, mas, com relação ao debug, é pior: ele exige alguma coisa de sqlite3 que não tem na Azure. Isso pode matar o deploy.

Para corrigir, recomendo deixar hardcoded `debug` como `false` no app.php. Não deu para fazer essa configuração por variável de ambiente.

**Comment by studiocuboweb** [comment]
@wgnann

Retirei o env var do debug e deixei apenas false conforme commit:
https://github.com/Transparencia-Brasil/transparencia.org.br/blob/master/config/app.php

Dessa forma se alguém mudar no env var não vai surtir efeito no site.

Estou fechando esse issue
