### ISSUE TITLE
Problema no cadastro de associação

### ISSUE THREAD

**Issue by studiocuboweb** [Transparencia-Brasil/transparencia.org.br#29]
Raul: tentei me cadastrar como associado, não funcionou. Mensagem de erro: "CakePHP: the rapid development php framework Um erro interno ocorreu. Error: An Internal Error Has Occurred".

**Comment by studiocuboweb** [comment]
@rdurl0 @JnCoe Agora o cadastro está funcionando.

o problema estava relacionado com a configuração do SMTP no disparo de email conforme issue #26 
o email de alerta de um novo associado estava configurado com o transport default

Para testar:
1. Acessar o formulário de associado e se cadastrar
2. abrir a caixa postal do email contato@transparencia.org.br
3. verificar se existe um email de alerta com o título "[transparencia.org.br] Novo associado para moderação: Paulo Campos"


Se os 3 passos estiverem funcionando, favor fechar esse issue

**Comment by rdurl0** [comment]
@pauloeducampos , @wgnann eu refiz o teste com **cadastro de associado** e com **doação**. Deu tudo certo. Fiz uma doação de teste e o fluxo de pagamento está funcionando bem, mas a página final retornou um erro.

O problema foi ao encerrar o processo. Quando terminamos de pagar via PayPal, aparece uma página dizendo que a transação foi um sucesso. Nessa página existe a opção "voltar para Transparência Brasil" e é clicando nele que aparece o erro da imagem.

![página de encerramento dá problema quando clica em "voltar para Transparência Brasil"](https://user-images.githubusercontent.com/22898231/115088442-8a9ace80-9ee6-11eb-87e8-09f96b1b2dd8.png)

![Provavelmente o link de retorno ao site está quebrado](https://user-images.githubusercontent.com/22898231/115088513-b1f19b80-9ee6-11eb-8482-386a64e6c58e.png)

**Comment by studiocuboweb** [comment]
@rdurl0 Criei a página https://www.transparencia.org.br/apoie/doacoes/confirmacao

Poderia validar se o texto / título estão conforme?

Fico aguardando eventuais ajustes... se estiver tudo certo, só fechar esse issue

**Comment by rdurl0** [comment]
Fiz uma doação como teste e deu certo. No final fui redirecionado para a página criada. :facepunch:
