### ISSUE TITLE
[admin] Ordenamento dos banners do carrossel home não funciona

### ISSUE THREAD

**Issue by studiocuboweb** [Transparencia-Brasil/transparencia.org.br#30]
Marina: Alteração da ordem dos banners não funciona (após alterar a ordem e clicar em "Salvar ordem", a lista volta ao estado original - com o banner mais recente no topo)

**Comment by studiocuboweb** [comment]
@rdurl0 @JnCoe Mais um issue resolvido.

O problema estava relacionado com case sensitive na programação. Pelo visto a nova hospedagem é case sensitive..

O objeto (nome da coluna) que salva a ordem no banco é Ordem, mas estava sendo utilizada no código como ordem. Mudei para Ordem e está funcionando.

Commit relacionado: https://github.com/Transparencia-Brasil/transparencia.org.br/commit/8499640e9359ea4720e7fa702599f8905244b504

Favor testar e se tiver tudo certo fechar o ticket

**Comment by rdurl0** [comment]
A Marina fez o teste e está tudo ok. Fechando a issue. 😃
