### ISSUE TITLE
[admin] cadastro de usuário: bloqueio e desbloqueio não funciona

### ISSUE THREAD

**Issue by studiocuboweb** [Transparencia-Brasil/transparencia.org.br#31]
Marina | testar fluxo de inclusão de novo usuário (incluir novos usuários e remover, verificar notificações) | Inclusão funciona; desbloqueio, não (se o box "Bloqueado" está ticado, não adianta desmarcar). Remover não é uma opção que existe.

**Comment by studiocuboweb** [comment]
Resolvido o problema

Para testar:
1. entrar no 
http://transparencia-site.azurewebsites.net/painel-ctl
2. Entrar em Usuários do sistema.
3. Selecionar ou criar um usuário já existente e selecionar / ativar a opção Bloqueado (Atenção para não bloquear o próprio usuário pq ele vai ficar travado)
4. Salvar
5. Deslogar
6. entrar novamente no painel-ctl e tentar se logar com o usuário bloquead
-> Comportamento esperado: A tela de login deve mostrar uma mensagem do tipo "usuário bloqueado". Nesse caso não é possível logar

7. se logar com o usuário normal (o que está desbloqueado) e desbloquear o usuário bloqueado
8. deslogar
9. tentar se logar com o usuário desbloqueado
-> Comportamento esperado: O usuário deve se logar no admin.

Se estiver tudo certo favor fechar o issue

commits:
https://github.com/Transparencia-Brasil/transparencia.org.br/commit/28c0fc564d666434b468015a03efbdb9ce3ea38c
https://github.com/Transparencia-Brasil/transparencia.org.br/commit/f746726b364595b0f2c6e8ad8f367f6144bb36bf

**Comment by rdurl0** [comment]
Testamos eu e a Marina com sucesso. Fechando a issue.
