### ISSUE TITLE
upload_max_filesize

### ISSUE THREAD

**Issue by wgnann** [Transparencia-Brasil/transparencia.org.br#33]
Era 20M configurado no servidor, agora precisará ser [configurado na aplicação](https://docs.microsoft.com/en-us/azure/app-service/configure-language-php?pivots=platform-linux).

**Comment by studiocuboweb** [comment]
Para aumentar o limite de upload de arquivo de 2MB para 20MB eu configurei os parametros no .htaccess conforme instruções do [link](https://docs.microsoft.com/en-us/azure/app-service/configure-language-php?pivots=platform-linux)  enviado pelo will neste issue.

Os parâmetros são esses:

    php_value upload_max_filesize 20M
    php_value post_max_size 60M
    php_value max_execution_time 360
    php_value max_input_time 360

@wgnann alguma consideração?

Agora o site permite uploads de até 20MB em qualquer seção do site (ex: banner e publicação)

Para impor limites por seção (banner 2mb e publicaçãoes 20mb) eu consigo fazer pelo código.  @mgaldino Posso criar um ticket para fazer essa implementação em todas as seções que permitem uploads de imagem / arquivo?
Considerando que se for imagem é até 2mb e arquivo até 20mb?

@rdurl0 eu testei por aqui, mas consegue também fazer uma validação por ai para ver se banners e publicações estão aceitando arquivos maiores de 2mb?

Fico no aguardo da resposta de vcs e do teste para efetivamente fechar esse issue

**Comment by studiocuboweb** [comment]
Conforme combinado na reunião:

1. Will validou os atributos php_value e vamos deixar dessa forma
2. Criarei um ticket no trello para fazer o controle do tamanho de arquivo por página dentro do cakephp
3. eu fiz a validação, fiz um upload de um arquivo maior que 2 megas e consegui subir.

Estou fechando esse ticket.
