### ISSUE TITLE
/opt/Kudu/KuduConsole/kudu.dll: Exec format error no deploy

### ISSUE THREAD

**Issue by studiocuboweb** [Transparencia-Brasil/transparencia.org.br#38]
@wgnann Mesmo problema que eu tive com o Achados e pedidos...

Me ajuda?

Valeu!

````
Akhenaton:transparencia.org.br pauloeduardocamposafonso$ git push azure master
Enumerating objects: 19, done.
Counting objects: 100% (19/19), done.
Delta compression using up to 8 threads
Compressing objects: 100% (11/11), done.
Writing objects: 100% (11/11), 4.73 KiB | 4.73 MiB/s, done.
Total 11 (delta 8), reused 0 (delta 0)
remote: Checking connectivity: 11, done.
remote: hooks/post-receive: 4: hooks/post-receive: /opt/Kudu/KuduConsole/kudu.dll: Exec format error
To https://transparencia-site.scm.azurewebsites.net:443/transparencia-site.git
   1b684f6..9c56d69  master -> master
````

**Comment by wgnann** [comment]
Parece haver algum bug com o deployment na Azure. Abri um support request lá para tentar entender por que está quebrando.

O que pareceu resolver:

1. acessar a instância via SSH;
2. mover o diretório `/home/site/repository` para outro lugar (e.g. `/home/site/exrepo`);
3. rodar `git push azure master` de novo.

**Comment by wgnann** [comment]
Depois de fazer uns testes, verificamos que o problema se tratava de um hook, `post-receive`, criado errado pelo deployer da MS. Aparentemente será corrigido.

O problema em si é que deveria ser `dotnet "$KUDU_EXE" "$KUDU_APPPATH" "$KUDU_MSBUILD" "$KUDU_DEPLOYER"` e, às vezes o executável `dotnet` é omitido.
