### ISSUE TITLE
validação no upload de arquivos de acordo com seções (até 2mb ou 20mb)

### ISSUE THREAD

**Issue by studiocuboweb** [Transparencia-Brasil/transparencia.org.br#39]
**Contexto**
https://transparencia.org.br/admin (necessário login)

- Criação e upload de arquivos / imagens

**Problema**
O limite máximo de upload de arquivo é 20mb configurado no php / hospedagem, porém existem seções do site (ex: banners) que devem permitir arquivos menores que 2mb (as imagens não devem ser pesadas para não sobrecarregar o site).

**Solução***
Aplicar validação personalizada para cada seção / formulário de criação e upload de conteúdo. 
Algumas seções devem permitir até 20mb (aquelas de publicações de relatórios / documentos e estudos) e outras permitir 2MB (para aquelas de upload de imagens)

***Roteiro de teste***
1. [Logar no administrador do site](https://transparencia.org.br/admin)

2. Financiamentos (até 20mb)
2.1. Criar um novo registro e fazer upload de arquivo menor ou igual  que 20mb (OK se subir)
2.2. fazer upload de arquivo maior que 20mb (OK se aparecer mensagem de erro)
2.3. clicar no botão salvar
2.4. ir no site área quem somos aba [transparência](https://transparencia.org.br/quem_somos#transparencia) e verificar se o arquivo está disponível para download
2.5. voltar no admin e editar o registro. Repetir o procedimento

3. Auditorias e contabilidade (até 20mb)
3.1. Criar um novo registro e fazer upload de arquivo menor ou igual que 20mb (OK se subir)
3.2. fazer upload de arquivo maior que 20mb (OK se aparecer mensagem de erro)
3.3. clicar no botão salvar
3.4. ir no site área quem somos aba [transparência](https://transparencia.org.br/quem_somos#transparencia) e verificar se o arquivo está disponível para download
3.5. voltar no admin e editar o registro. Repetir o procedimento 

4. Relatórios de atividades (até 20mb)
4.1. Criar um novo registro e fazer upload de arquivo menor ou igual que 20mb (OK se subir)
4.2. fazer upload de arquivo maior que 20mb (OK se aparecer mensagem de erro)
4.3. clicar no botão salvar
4.4. ir no site área quem somos aba [transparência](https://transparencia.org.br/quem_somos#transparencia) e verificar se o arquivo está disponível para download
4.5. voltar no admin e editar o registro. Repetir o procedimento 

5. Banners (até 2mb)
5.1. Criar um novo registro e fazer upload de uma imagem maior que 2mb e clicar no botão salvar (Ok se retornar mensagem de erro)
5.2. selecionar um novo arquivo menor ou igual a 2mb, fazer upload e clicar no botão salvar (OK se salvar)
5.3. verificar se o banner aparece na [home do site ](https://transparencia.org.br/)
5.4. voltar no admin e editar o registro. repetir o procedimento

6. Projetos (até 2mb)
6.1. Criar um novo registro e fazer upload de uma imagem (Logotipo) maior ou igual a 2mb e uma imagem (imagem de fundo) maior ou igual a 2mb  e clicar no botão salvar (Ok se retornar mensagem de erro)
6.2. selecionar novos arquivo menor ou igual a 2mb, fazer upload e clicar no botão salvar (OK se salvar)
6.3. verificar se os arquivos aparecem na [página do projeto ](https://transparencia.org.br/projetos)
6.4. voltar no admin e editar o registro. repetir o procedimento

7. Publicações (até 20mb)
7.1. Selecionar uma categoria (ex: Aritgos) e clicar no botão verde (lupa)
7.2. Clicar em nova publicação
7.3. Preencher o formulário e escolher um arquivo maior que 20mb. clicar em salvar (OK se apareceu mensagem de erro)
7.4. Escolher um novo arquivo menor ou igual que 20mb. clicar em salvar (Ok se salvar)
7.5. Verificar em [publicações](https://transparencia.org.br/publicacoes) se o arquivo existe (fazer download do arquivo)
7.6. Repetir os passos, mas dessa vez editando o registro criado.

8. Blog (não está sendo usado. nao precisa testar)
9. Mídia (não está sendo usado. nao precisa testar)

10. Notícias (até 2mb)
10.1. Criar um novo registro e fazer upload de uma imagem maior que 2mb e clicar no botão salvar (Ok se retornar mensagem de erro)
10.2. selecionar um novo arquivo menor ou igual a 2mb, fazer upload e clicar no botão salvar (OK se salvar)
10.3. verificar se o banner aparece na [página de notícias do site ](https://transparencia.org.br/noticias)
10.4. voltar no admin e editar o registro. repetir o procedimento

11. Quem somos (até 2mb)
11.1. Criar um novo registro e fazer upload de uma imagem maior que 2mb e clicar no botão salvar (Ok se retornar mensagem de erro)
11.2. selecionar um novo arquivo menor ou igual a 2mb, fazer upload e clicar no botão salvar (OK se salvar)
11.3. verificar se o banner aparece na [página quem somos do site  / aba estrutura](https://transparencia.org.br/quem_somos#quem_somos)
11.4. voltar no admin e editar o registro. repetir o procedimento

**Comment by studiocuboweb** [comment]
@mgaldino @mgaldino @JnCoe 

Caros, irei subir na segunda feira a umas 10:00 da manhã.

Após a publicação eu aviso vocês e seria bom fazer uma dupla checagem utilizando o roteiro criado na descrição desse issue.

É meio longo, mas não demorado..

**Comment by maiatoji** [comment]
Item 2, 5, 6, 7, 10 e 11: ✅ 
Itens 3 e 4 (são iguais): ❌ ao editar a entrada e deletar o anexo, as informações dos campos de formulário são limpas e a entrada permanece na lista do admin e na página transparência (onde o anexo deletado continua disponível). Ao tentar deletar mais uma vez o anexo, aparece uma mensagem de erro:

![image](https://user-images.githubusercontent.com/80543612/123151448-d8c5d400-d439-11eb-849e-88138da56290.png)

Item 8: 🟡 O erro não é exibido como uma mensagem na própria página, mas em uma nova página - o que é ruim porque quando se volta ao formulário os dados preenchidos são apagados e têm que ser preenchidos de novo

![image](https://user-images.githubusercontent.com/80543612/123150824-2db51a80-d439-11eb-9924-2036d0ab852e.png)

**Comment by studiocuboweb** [comment]
Oi Marina,

Boa tarde.

Esse erro está acontecendo provavelmente porque você está subindo o arquivo
com acento. O nome do arquivo deve ser sem acento, espaço e outros
caracteres que não sejam alfanumérico (com exceção de - e _)

Já existe um ticket para fazer esse ajuste e permitir arquivos com
acentos...

Abraço

**Comment by maiatoji** [comment]
Refiz o teste dos itens 3 e 4 com arquivo sem acentos e deu a mesma coisa...

Acima, onde está escrito item 8, leia-se item 10. Realmente seria ideal se a mensagem de erro sobre o tamanho da imagem aparecer na mesma página, não em página diferente.

**Comment by studiocuboweb** [comment]
@maiatoji 
O item 4 foi substituído de Auditorias e contabilidade (que estava repetido com o item 3) para Relatórios de atividades.

O problema que acontecia com o Item 3 foi resolvido.
Agora ao editar uma entrada em Auditorias e contabilidade e apagar um arquivo o sistema não zera o formulário e o arquivo é deletado corretamente tanto no admin quanto na [página de transparência](https://www.transparencia.org.br/quem_somos#transparencia) onde o relatório é apresentado.

Pull request do fix:
https://github.com/Transparencia-Brasil/transparencia.org.br/pull/43

O Item 8 sobre o erro do tamanho do arquivo foi corrigido. Agora o erro aparece corretamente na página da entrada e não em uma página de erro conforme imagem:
![Screen Shot 2021-07-20 at 12 09 59](https://user-images.githubusercontent.com/32527574/126349673-890805c1-e39e-4737-8898-8cf14f185a8c.png)


Commit do fix:
https://github.com/Transparencia-Brasil/transparencia.org.br/commit/994463a0af92b949275924f31e8c8dc26f0c4eca

Os dois ajustes já estão publicados em produção e testados por mim.

Estou encerrando esse issue e caso algo apareça novamente, podemos reabri-lo ou criar um novo.
