### ISSUE TITLE
algumas imagens estão faltando

### ISSUE THREAD

**Issue by wgnann** [Transparencia-Brasil/transparencia.org.br#4]
Ex:
`carrossel%20newsletter-07-07-07-07-07-07.jpg`
`Banner_Home_Nova_Marca.png`

**Comment by studiocuboweb** [comment]
@wgnann (copiando @rdurl0 @JnCoe) 

[Pull request WIP feito](https://github.com/Transparencia-Brasil/transparencia.org.br/pull/17) (Não vamos fazer o merge ainda porque pode quebrar o site atual hospedado no Linode.

Atualizei o readme.md com as pastas que a nova estrutura vai possuir (elas estão no gitignore e por isso não entraram no repositório).

Estrutura nova
webroot/
    uploads/
        banners/
        imprensa/
        midias/
        projetos/
        publicacoes/
        quemsomos/
        financiamentos/
        auditoriascontabilidade/
        relatoriosatividades/

+ Symlink 
ln -s uploads downloads

Se você quiser mover os arquivos no Linode para a estrutura atual no Azure, segue o mapa:

img/banners -> uploads/banners

img/imprensa ->uploads/imprensa

downloads/midias -> uploads/midias (creio que não tenha nada nessa pasta ou um arquivo de teste)

img/projetos -> uploads/projetos

downloads/publicacoes ->uploads/publicacoes

img/quemsomos  -> uploads/quemsomos

uploads/financiamentos -> uploads/financiamentos

uploads/auditoriascontabilidade -> uploads/auditoriascontabilidade

uploads/relatoriosatividades -> uploads/relatoriosatividades


Obs: Alguns links de imagens, páginas e arquivos estavam com caminho absoluto e eu mudei para relativo, dessa forma funciona em qualquer URL / ambiente. Com exceção da URL para o blog que continua com o endereço completo da transparência pq é outro site.

O Ajuste mais pesado foi na página do projeto-obra transparente. Mudei várias URLS lá. (só para deixar anotado e testar depois).

Não podemos fazer o merge no main agora porque vai comprometer o ambiente no linode. 
O que você acha de criarmos um novo branch main-v2?

Obs2: Os arquivos e pastas dentro de img e listados aqui foram deletados do git e transferidos para a pasta UPLOADS e não serão mais armazenadas no git (a pasta uploads está no gitignore)

Blz?

**Comment by studiocuboweb** [comment]
@wgnann (copiando @rdurl0 @JnCoe)

Acabei de concluir o pull request. Agora o branch pasta-assets-dinamicos foi deletado e os ajustes de pasta já estão mergeados no main.

Estou fechando esse issue
