### ISSUE TITLE
Preview de posts em FB e Twitter

### ISSUE THREAD

**Issue by maiatoji** [Transparencia-Brasil/transparencia.org.br#44]
Olá,

Não é urgentíssimo, mas é importante:

No FB e no Twitter, o preview do post do blog puxa o logo antigo da TB. Poderiam, por favor, configurar para puxar o logo novo ou só o círculo com o T?

<img src="https://user-images.githubusercontent.com/80543612/126663349-923064fd-6c03-4ace-bf9e-bea8f7652078.png" width="500">

<img src="https://user-images.githubusercontent.com/80543612/126662905-56191232-7193-4f8e-ab90-fa66712af4a8.png" width="500">

Obrigada :)

**Comment by andremotasc** [comment]
Oi @maiatoji 
Está feito.

Foi complicado encontrar o problema.
Existia um plugin chamado OG que estava conflitando com as configurações do YoastSEO.
Estava inclusive deixando o blog sem o favico na aba do browser.

Desativamos o OG (Mas não deletamos o plugin) e voltou a funcionar.

Queria saber por que esse plugin foi instalado.
Conforme for podemos procurar por outras saídas para resolver a necessidade de vocês sem precisar utilizá-lo novamente.

Abraços,

**Comment by maiatoji** [comment]
Obrigada, @wgnann 

Fiz um teste e funcionou para o FB, mas não [para o Twitter](https://twitter.com/trbrasil/status/1421117585358311433), onde ao logo antigo continua aparecendo...

Quanto ao OG, não tenho ideia do motivo pelo qual está instalado (já estava aí quando cheguei, rs. Talvez @mgaldino consiga dizer). Mas pelo que entendi, o propósito dele é justamente fazer os previews dos posts do blog mais visualmente atraentes em redes sociais, puxando uma imagem inserida no post para o preview, por exemplo.

**Comment by andremotasc** [comment]
@maiatoji qual link não está correto no Twitter?
Fiz novamente alguns testes por aqui e todos abriram corretamente....
