### ISSUE TITLE
publicações desapareceram

### ISSUE THREAD

**Issue by wgnann** [Transparencia-Brasil/transparencia.org.br#46]
não tem a ver com `APP_URL`. parece ser algo relacionado a um tal de `base.css`.

**Comment by studiocuboweb** [comment]
@wgnann Não entendi muito bem esse issue, mas creio que com a correção do encode do banco as publicações voltaram a aparecer:

https://www.transparencia.org.br/publicacoes

testei aqui e até com filtros e a lista aparece normalmente.

Se for isso mesmo, pode fechar esse issue?
